'use client'
import { db } from '@/utils/db'
import { UserAnswer } from '@/utils/schema'
import { eq } from 'drizzle-orm'
import React, { useEffect, useState, use } from 'react'
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/collapsible"
import { 
    ChevronDown, 
    Star, 
    CheckCircle2, 
    AlertCircle, 
    Award, 
    ArrowLeft, 
    Trophy,
    Target,
    Zap,
    History,
    ChevronLeft,
    Sparkles
} from 'lucide-react'
import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { motion } from 'framer-motion'
import { Card, CardContent } from '@/components/ui/card'

function Feedback({ params }) {
  const { interviewId } = use(params);
  const [feedbackList, setFeedbackList] = useState([]);
  const [overallRating, setOverallRating] = useState(0);
  const [loading, setLoading] = useState(true);
  const router = useRouter();

  useEffect(() => {
    GetFeedback();
  }, [interviewId]);

  const GetFeedback = async () => {
    try {
        setLoading(true);
        const result = await db.select()
          .from(UserAnswer)
          .where(eq(UserAnswer.mockIdRef, interviewId))
          .orderBy(UserAnswer.id);

        setFeedbackList(result);
        
        if (result.length > 0) {
          const sum = result.reduce((acc, item) => acc + (Number(item.rating) || 0), 0);
          setOverallRating((sum / result.length).toFixed(1));
        }
    } catch (error) {
        console.error("Error fetching feedback:", error);
    } finally {
        setLoading(false);
    }
  }

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] gap-4">
        <div className="w-12 h-12 border-4 border-indigo-200 border-t-indigo-600 rounded-full animate-spin"></div>
        <p className="text-gray-500 font-bold animate-pulse">Computing AI Analysis...</p>
      </div>
    );
  }

  return (
    <div className='flex flex-col gap-10'>
        {/* Header Section */}
        <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
                <Button variant="ghost" size="icon" onClick={() => router.replace('/dashboard')} className="rounded-xl">
                    <ChevronLeft size={24} />
                </Button>
                <div>
                    <h1 className='text-3xl font-black tracking-tight text-gray-900 dark:text-white font-serif'>
                        Post-Interview Analysis
                    </h1>
                    <p className="text-gray-500 dark:text-gray-400 font-medium tracking-tight">Comprehensive report generated by AI Prep Engine.</p>
                </div>
            </div>
            
            <Button 
                onClick={() => router.replace('/dashboard')}
                className="hidden md:flex bg-indigo-600 hover:bg-indigo-700 text-white rounded-2xl px-6 h-12 font-bold shadow-lg shadow-indigo-600/20"
            >
                Back to Dashboard
            </Button>
        </div>

        {/* Hero Summary Card */}
        <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className='bg-white dark:bg-gray-900 p-10 rounded-[40px] shadow-sm border border-gray-100 dark:border-gray-800 relative overflow-hidden'
        >
            <div className='absolute top-[-50px] right-[-50px] w-64 h-64 bg-indigo-600/5 rounded-full blur-3xl' />
            
            <div className="flex flex-col lg:flex-row items-center gap-12 relative z-10">
                <div className="relative">
                    <div className="w-48 h-48 rounded-full border-[12px] border-indigo-50 dark:border-indigo-950/50 flex flex-col items-center justify-center bg-white dark:bg-gray-950 shadow-inner">
                        <span className="text-6xl font-black text-indigo-600 tracking-tighter">{overallRating}</span>
                        <span className="text-xs font-black text-indigo-400 uppercase tracking-widest mt-1">Score / 10</span>
                    </div>
                    {overallRating >= 8 && (
                        <div className="absolute -top-2 -right-2 bg-yellow-400 p-3 rounded-full shadow-lg border-4 border-white dark:border-gray-900 animate-bounce">
                            <Trophy className="text-white" size={20} />
                        </div>
                    )}
                </div>

                <div className="flex-1 text-center lg:text-left">
                    <div className="flex flex-wrap items-center justify-center lg:justify-start gap-3 mb-6">
                        <div className={`px-4 py-1.5 rounded-full text-xs font-black uppercase tracking-widest border ${
                            overallRating >= 8 ? 'bg-green-50 text-green-600 border-green-100' : 
                            overallRating >= 5 ? 'bg-blue-50 text-blue-600 border-blue-100' : 
                            'bg-red-50 text-red-600 border-red-100'
                        }`}>
                            Result: {overallRating >= 8 ? 'Excellent Performance' : overallRating >= 5 ? 'Strong Potential' : 'Needs Technical Polish'}
                        </div>
                        <div className="px-4 py-1.5 rounded-full text-xs font-black uppercase tracking-widest bg-gray-50 dark:bg-gray-800 text-gray-500 dark:text-gray-400 border border-gray-100 dark:border-gray-700">
                           {feedbackList.length} Units Analyzed
                        </div>
                    </div>
                    
                    <h2 className='text-3xl font-black text-gray-900 dark:text-white mb-4 leading-tight'>
                        {overallRating >= 8 ? 'You’re ready for the spotlight!' : 'Good effort! Let’s sharpen those skills.'}
                    </h2>
                    <p className='text-gray-500 dark:text-gray-400 font-medium mb-8 max-w-2xl text-lg'>
                        Our AI has analyzed your audio patterns and technical depth. Below are specific action items to help you bridge the gap to expert level.
                    </p>
                    
                    <div className="flex flex-wrap justify-center lg:justify-start gap-4">
                        <div className="flex items-center gap-2 text-sm font-bold text-gray-700 dark:text-gray-300">
                            <Target size={18} className="text-indigo-600" />
                            Targeted Role: <span className="text-indigo-600">{feedbackList[0]?.category || 'Technical'}</span>
                        </div>
                        <div className="flex items-center gap-2 text-sm font-bold text-gray-700 dark:text-gray-300">
                            <Zap size={18} className="text-indigo-600" />
                            AI Confidence: <span className="text-indigo-600">98.4%</span>
                        </div>
                    </div>
                </div>
            </div>
        </motion.div>

        {/* Detailed Feedback Header */}
        <div className="flex items-center gap-4 px-4">
            <div className="w-12 h-1 bg-indigo-600 rounded-full" />
            <h2 className='text-xl font-black text-gray-900 dark:text-white uppercase tracking-widest flex items-center gap-3'>
                <History size={20} className="text-indigo-600" />
                Deeper Breakdown
            </h2>
        </div>

        {/* Collapsible List */}
        <div className="space-y-6">
            {feedbackList && feedbackList.map((item, index) => (
                <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: index * 0.1 }}
                >
                    <Collapsible className='group'>
                        <CollapsibleTrigger className='w-full text-left'>
                            <div className='p-8 bg-white dark:bg-gray-900 rounded-[32px] flex justify-between items-center shadow-sm border border-gray-100 dark:border-gray-800 group-hover:shadow-xl group-hover:border-indigo-100 dark:group-hover:border-indigo-900 transition-all duration-300'>
                                <div className="flex gap-6 items-center">
                                    <div className="bg-gradient-to-br from-indigo-600 to-blue-500 text-white w-12 h-12 rounded-2xl flex items-center justify-center font-black text-xl shrink-0 shadow-lg shadow-indigo-600/20">
                                        {index + 1}
                                    </div>
                                    <h3 className="font-bold text-lg text-gray-800 dark:text-white leading-tight pr-4">
                                        {item.question}
                                    </h3>
                                </div>
                                <div className="flex items-center gap-6 shrink-0">
                                    <div className={`hidden md:flex px-4 py-2 rounded-xl text-xs font-black uppercase tracking-widest ${
                                        Number(item.rating) >= 8 ? 'bg-green-50 text-green-600' : 
                                        Number(item.rating) >= 5 ? 'bg-blue-50 text-blue-600' : 
                                        'bg-red-50 text-red-600'
                                    }`}>
                                        Rating: {item.rating}/10
                                    </div>
                                    <div className="p-2 bg-gray-50 dark:bg-gray-800 rounded-full text-gray-400 group-data-[state=open]:rotate-180 transition-transform">
                                        <ChevronDown size={20} />
                                    </div>
                                </div>
                            </div>
                        </CollapsibleTrigger>
                        <CollapsibleContent>
                            <motion.div 
                                initial={{ opacity: 0, height: 0 }}
                                animate={{ opacity: 1, height: 'auto' }}
                                className='mt-3 p-8 bg-gray-50 dark:bg-gray-950 rounded-[40px] border border-gray-100 dark:border-gray-800 flex flex-col gap-8'
                            >
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                    <div className="space-y-3">
                                        <div className="flex items-center gap-2 text-indigo-600 dark:text-indigo-400">
                                            <Sparkles size={16} fill="currentColor" />
                                            <h4 className="text-[10px] font-black uppercase tracking-widest">Target Ideal Response</h4>
                                        </div>
                                        <div className="p-5 bg-white dark:bg-gray-900 rounded-[24px] border border-indigo-50 dark:border-indigo-900/40 text-sm font-medium text-gray-700 dark:text-gray-300 leading-relaxed shadow-sm">
                                            {item.correctAns}
                                        </div>
                                    </div>
                                    
                                    <div className="space-y-3">
                                        <div className="flex items-center gap-2 text-gray-400">
                                            <UserAnswerIcon size={16} />
                                            <h4 className="text-[10px] font-black uppercase tracking-widest">Your Recorded Input</h4>
                                        </div>
                                        <div className="p-5 bg-gray-100 dark:bg-gray-800 rounded-[24px] border border-gray-200 dark:border-gray-700 text-sm font-medium text-gray-600 dark:text-gray-400 leading-relaxed italic">
                                            "{item.userAns}"
                                        </div>
                                    </div>
                                </div>

                                <div className="p-6 bg-gradient-to-r from-indigo-50 to-blue-50 dark:from-indigo-950/30 dark:to-blue-950/30 rounded-[24px] border border-indigo-100/50 dark:border-indigo-900/50">
                                    <div className="flex items-center gap-2 text-indigo-600 dark:text-indigo-400 mb-3">
                                        <Award size={18} />
                                        <h4 className="text-[10px] font-black uppercase tracking-widest">AI Feedback & Action Items</h4>
                                    </div>
                                    <p className="text-indigo-900 dark:text-indigo-200 text-sm font-bold leading-relaxed">
                                        {item.feedback}
                                    </p>
                                </div>
                            </motion.div>
                        </CollapsibleContent>
                    </Collapsible>
                </motion.div>
            ))}
        </div>

        {/* Footer Action */}
        <div className="py-10 text-center">
            <Button 
                onClick={() => router.replace('/dashboard')}
                className="bg-indigo-600 hover:bg-indigo-700 text-white rounded-3xl px-12 h-16 text-xl font-black shadow-2xl shadow-indigo-600/30 active:scale-95 transition-all"
            >
                Return to Command Center
            </Button>
            <p className="text-gray-400 text-xs font-bold uppercase tracking-widest mt-6">Prepared for {feedbackList[0]?.userEmail}</p>
        </div>
    </div>
  )
}

function UserAnswerIcon({ size }) {
    return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M12 2C6.48 2 2 6.48 2 12C2 17.52 6.48 22 12 22C17.52 22 22 17.52 22 12C22 6.48 17.52 2 12 2ZM12 20C7.59 20 4 16.41 4 12C4 7.59 7.59 4 12 4C16.41 4 20 7.59 20 12C20 16.41 16.41 20 12 20ZM7 12L12 17L17 12H13V7H11V12H7Z" fill="currentColor"/>
    </svg>
}

export default Feedback
